layout_spectrum: 0.30497638625092804
typography_spectrum: 0.6488608112558722
color:
  brandStrength: 0.8401519663166255
  lightness: 0.06362959160469472
  saturation: 0.4647229923866689
  rhythmicContrast: 0.9493930719327182
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: The Zero Daily
